### ISSUE TITLE
Add Signals in Support of Measurement Paper

### ISSUE THREAD

**Issue by jinksunk** [jinksunk/KIDSDevelopment#6]
Need to add the following signals:

| Domain | Constraint | Value |
| --- | --- | --- |
| HTTP Get Request Resource | String Match | "default.ida" |
| HTTP Get Request Parameter | String Match | 'NNNN...' |
| TCP Destination Port Number | Integer Equality | 80 |
| TCP packet data size > 239 bytes | Integer Inequality | > 239 |
| TCP Flag Set | Snort Specification | 'A+' |
| TCP Data Content | Byte Match at Position | —2F646566 61756C74 2E696461 3F4E4E4E—@64 |
| HTTP Get Request Size Percentile | Integer Inequality | > 98 |
| Source IP Address | IPv4 Range Set Membership | [0.0.0.0- 172.196.11.255;172.196.13.1- 255.255.255.255] |
##### ToDo:
- [x] Add support for each signal domain [following guide](https://www.semantiknit.com/mwiki2/index.php/How_to_Add_Support_For_A_New_SignalDomain)
- [x] Add support for each constraint type [following guide](https://www.semantiknit.com/mwiki2/index.php/How_to_Add_Support_For_A_New_SignalConstraint)
- [x] Add each signal specification to the ontology [following guide](https://www.semantiknit.com/mwiki2/index.php/How_to_Add_Support_For_A_New_Signal)
